V=FunctionSpace(mesh2,"CG",2)
#R=FunctionSpace(mesh2,"R",0)
#W=V*R
#(u,c)=TrialFunction(W)
u=TrialFunction(V)
#(v,d)=TestFunction(W)
v=TestFunction(V)
dS=Measure("dS")[boundaries]
#dx=Measure("dx")[interior]
f=Expression('x[0]*x[0]+x[1]*x[1]+x[2]*x[2]')
#a=(dot(grad(u),grad(v))+u*d+v*c)*dx(5)
a=dot(grad(u),grad(v))*dx
p=Constant('1.0')
n=FacetNormal(mesh2)
L=f*v*dx+p*avg(v)*dS(4)
#L=f*v*dx
#bc=DirichletBC(V,bvals,boundaries,4)
A=assemble(a,tensor=None)
b=assemble(L,tensor=None)
#w=Function(W)
u=Function(V)

